<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Epidemiology Methods lecture notes - 13&nbsp; Example data analysis in YRBS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapt12.html" rel="next">
<link href="./chapt10.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Example data analysis in YRBS</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Epidemiology Methods lecture notes</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction: Types of studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chaptA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data displays</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Identifying research questions and data sources</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Testing hypotheses</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Associations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt5.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Causality vs association</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt6.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Excess risk</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt7.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Measurement error and screening</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt8.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confounding and linear regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt9.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Confounding and causal graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt10.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Ecological studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt11.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Example data analysis in YRBS</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt12.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Survey data analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt13.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Randomized experiments and quasi-experiments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt14.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cohort studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt15.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Case-control studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary-of-statistical-methods" id="toc-summary-of-statistical-methods" class="nav-link active" data-scroll-target="#summary-of-statistical-methods"><span class="toc-section-number">13.1</span>  Summary of statistical methods</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="toc-section-number">13.2</span>  Logistic regression</a>
  <ul class="collapse">
  <li><a href="#variable-selection-and-coding-for-data-analysis" id="toc-variable-selection-and-coding-for-data-analysis" class="nav-link" data-scroll-target="#variable-selection-and-coding-for-data-analysis"><span class="toc-section-number">13.2.1</span>  Variable selection and coding for data analysis</a></li>
  <li><a href="#examples-of-logistic-regression-in-yrbs" id="toc-examples-of-logistic-regression-in-yrbs" class="nav-link" data-scroll-target="#examples-of-logistic-regression-in-yrbs"><span class="toc-section-number">13.2.2</span>  Examples of logistic regression in YRBS</a></li>
  </ul></li>
  <li><a href="#strength-training-and-sexual-partners" id="toc-strength-training-and-sexual-partners" class="nav-link" data-scroll-target="#strength-training-and-sexual-partners"><span class="toc-section-number">13.3</span>  Strength training and sexual partners</a>
  <ul class="collapse">
  <li><a href="#define-variables" id="toc-define-variables" class="nav-link" data-scroll-target="#define-variables"><span class="toc-section-number">13.3.1</span>  Define variables</a></li>
  <li><a href="#crude-odds-ratio" id="toc-crude-odds-ratio" class="nav-link" data-scroll-target="#crude-odds-ratio"><span class="toc-section-number">13.3.2</span>  Crude odds ratio</a></li>
  <li><a href="#adjusted-odds-ratio" id="toc-adjusted-odds-ratio" class="nav-link" data-scroll-target="#adjusted-odds-ratio"><span class="toc-section-number">13.3.3</span>  Adjusted odds ratio</a></li>
  <li><a href="#example-asthma-and-smoking" id="toc-example-asthma-and-smoking" class="nav-link" data-scroll-target="#example-asthma-and-smoking"><span class="toc-section-number">13.3.4</span>  Example: asthma and smoking</a></li>
  <li><a href="#example-suicidal-ideation-and-grades-in-school" id="toc-example-suicidal-ideation-and-grades-in-school" class="nav-link" data-scroll-target="#example-suicidal-ideation-and-grades-in-school"><span class="toc-section-number">13.3.5</span>  Example: suicidal ideation and grades in school</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Example data analysis in YRBS</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="summary-of-statistical-methods" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="summary-of-statistical-methods"><span class="header-section-number">13.1</span> Summary of statistical methods</h2>
<p>Recall the table from chapter 1 for summarizing data from categorical (C) and quantitative (Q) variables. The types of analysis depend on the types of data.</p>
<p>We divide data into categorical (C) and quantitative (Q). The types of analysis depend on the types of data.</p>
<p>Categorical variables can further be categorized as ordinal or non-ordinal.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable type</th>
<th style="text-align: left;">Outcome Quantitative</th>
<th style="text-align: left;">Outcome Categorical</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Predictor quantitative</td>
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow Q\)</span></td>
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow C\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Predictor categorical</td>
<td style="text-align: left;"><span class="math inline">\(C \rightarrow Q\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C \rightarrow C\)</span></td>
</tr>
</tbody>
</table>
<p>The displays and analysis types are not meant to correspond to each other.</p>
<p>This table is not meant to be a cookbook. This table demonstrates that some types of analysis definitely do not make sense for some types of data. E.g., scatterplot cannot be used instead of 2x2 table.</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 47%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Data</th>
<th style="text-align: left;">Display</th>
<th style="text-align: left;">Analysis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow Q\)</span></td>
<td style="text-align: left;">scatterplots (xyplot)</td>
<td style="text-align: left;">linear regression (lm)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow C\)</span> or <span class="math inline">\(C \rightarrow Q\)</span></td>
<td style="text-align: left;">Box and whisker plot (bwplot)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">dotplot (w or w/o confidence interval)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Categorical variable is binary</td>
<td style="text-align: left;">stratified density plot (densityplot)</td>
<td style="text-align: left;">t-test, Wilcoxon</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Categorical variable is binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Logistic regression glm( , family=binomial)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Categorical variable is not binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">test for trend (if ordinal): e.g., Cuzick’s</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Categorical variable is not binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Tukey’s HSD (anova followesd by TukeyHSD)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Categorical variable is not binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">transform to binary and use above methods</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(C \rightarrow C\)</span></td>
<td style="text-align: left;">Contingency table (tally)</td>
<td style="text-align: left;">chi-square test (chisq.test)</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Kruskal-Wallis test (kruskal.test)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">pairwise chi-square test</td>
</tr>
</tbody>
</table>
</section>
<section id="logistic-regression" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">13.2</span> Logistic regression</h2>
<p>The regression type that you use is determined by your outcome variable, not by your predictors. Many outcome variables are binary/dichotomous: that is, they take only the values 0 or 1 (or FALSE and TRUE). You can model binary outcome variables with four different methods: logistic regression, Poisson regression, ordinary linear regression, and probit regression. Logistic regression is most commonly used in public health.</p>
<p>The coefficients in a logistic regression are log odds ratios; many statistical programs will transform them automatically for you. The predicted values from a logistic regression are the estimated probabilities of the event occurring.</p>
<section id="variable-selection-and-coding-for-data-analysis" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="variable-selection-and-coding-for-data-analysis"><span class="header-section-number">13.2.1</span> Variable selection and coding for data analysis</h3>
<p>There are many guidelines for identifying covariates for data analysis. Here are some ideas: • Important demographic features: socioeconomic status, race/ethnicity, gender, age. These may be important to control for, even if non-significant. • Variables predicted to be potential confounders by relevant theories: e.g., health behavior theories often include a construct relevant to self-efficacy to carry out a health behavior. • Variables used as control variables in other papers can suggest both which theories are important and empirically which variables are important.</p>
</section>
<section id="examples-of-logistic-regression-in-yrbs" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="examples-of-logistic-regression-in-yrbs"><span class="header-section-number">13.2.2</span> Examples of logistic regression in YRBS</h3>
<p>We start out by defining necessary variables. I rename everything so that I can read the output more easily. I also change factors to a scale that makes sense. For all varaibles, consult the codebook. Each variable is listed at least twice: first, to show the wording of the question and the answer choices followed by a dichotomized version (if applicable); second, to show the distribution of the variable (how many respondents gave each answer) and the coding (e.g., 1 = yes and 2 = no). For creating new variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting new variable to be true if old variable is 1 and 0 otherwise</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>newvariable<span class="ot">=</span>yrbs<span class="sc">$</span>oldvariable<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># check it did what you expected tally(newvariable ~ oldvariable, data=yrbs)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Load necessary libraries and data. We are using a new library here called arm because it displays regression analysis results compactly. Check data has expected number of variables (columns) and observations (rows).</p>
<p>We use the Stata format because it reliably keeps the labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readstata13)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arm)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>yrbs<span class="ot">=</span><span class="fu">read.dta13</span>(<span class="st">"yrbs2019.dta"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13677   235</code></pre>
</div>
</div>
<p>Age is originally on a scale from 1 to 7, but I express it as the actual age in years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>Q1, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Q1
12 years old or younger            13 years old            14 years old 
                     60                      27                    1699 
           15 years old            16 years old            17 years old 
                   3473                    3628                    3102 
  18 years old or older                    &lt;NA&gt; 
                   1616                      72 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>age <span class="ot">=</span> <span class="fu">as.numeric</span>(yrbs<span class="sc">$</span>Q1)<span class="sc">+</span><span class="dv">11</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(Q1<span class="sc">~</span>age, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         age
Q1                          12   13   14   15   16   17   18 &lt;NA&gt;
  12 years old or younger   60    0    0    0    0    0    0    0
  13 years old               0   27    0    0    0    0    0    0
  14 years old               0    0 1699    0    0    0    0    0
  15 years old               0    0    0 3473    0    0    0    0
  16 years old               0    0    0    0 3628    0    0    0
  17 years old               0    0    0    0    0 3102    0    0
  18 years old or older      0    0    0    0    0    0 1616    0
  &lt;NA&gt;                       0    0    0    0    0    0    0   72</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>female<span class="ot">=</span> yrbs<span class="sc">$</span>Q2<span class="sc">==</span><span class="st">"Female"</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(Q2<span class="sc">~</span>female, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        female
Q2       TRUE FALSE &lt;NA&gt;
  Female 6885     0    0
  Male      0  6641    0
  &lt;NA&gt;      0     0  151</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define race/ethnicity categories</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>black<span class="ot">=</span>yrbs<span class="sc">$</span>raceeth<span class="sc">==</span><span class="st">"black or african american"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(black <span class="sc">~</span> raceeth, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       raceeth
black   Am Indian/Alaska Native Asian Black or African American
  TRUE                        0     0                         0
  FALSE                     145   618                      2040
  &lt;NA&gt;                        0     0                         0
       raceeth
black   Native Hawaiian/Other PI White Hispanic / Latino Multiple - Hispanic
  TRUE                         0     0                 0                   0
  FALSE                       69  6668              1009                2029
  &lt;NA&gt;                         0     0                 0                   0
       raceeth
black   Multiple - Non-Hispanic &lt;NA&gt;
  TRUE                        0    0
  FALSE                     661    0
  &lt;NA&gt;                        0  438</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>hispanic<span class="ot">=</span>(yrbs<span class="sc">$</span>raceeth<span class="sc">==</span><span class="st">"hispanic / latino"</span> <span class="sc">|</span> yrbs<span class="sc">$</span>raceeth<span class="sc">==</span><span class="st">"multiple - hispanic"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(hispanic <span class="sc">~</span> raceeth, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        raceeth
hispanic Am Indian/Alaska Native Asian Black or African American
   TRUE                        0     0                         0
   FALSE                     145   618                      2040
   &lt;NA&gt;                        0     0                         0
        raceeth
hispanic Native Hawaiian/Other PI White Hispanic / Latino Multiple - Hispanic
   TRUE                         0     0                 0                   0
   FALSE                       69  6668              1009                2029
   &lt;NA&gt;                         0     0                 0                   0
        raceeth
hispanic Multiple - Non-Hispanic &lt;NA&gt;
   TRUE                        0    0
   FALSE                     661    0
   &lt;NA&gt;                        0  438</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>white<span class="ot">=</span>yrbs<span class="sc">$</span>raceeth<span class="sc">==</span><span class="st">"white"</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>asian<span class="ot">=</span>yrbs<span class="sc">$</span>raceeth<span class="sc">==</span><span class="st">"asian"</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>multi.nonhispanic<span class="ot">=</span>yrbs<span class="sc">$</span>raceeth<span class="sc">==</span><span class="st">"multiple - non-hispanic"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Grade in school. Set grade to missing if grade is 13.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>grade<span class="ot">=</span><span class="fu">as.numeric</span>(yrbs<span class="sc">$</span>Q3)<span class="sc">+</span><span class="dv">8</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">is.na</span>(yrbs<span class="sc">$</span>grade)<span class="ot">=</span>yrbs<span class="sc">$</span>grade<span class="sc">==</span><span class="dv">13</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>grade, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>grade
   9   10   11   12 &lt;NA&gt; 
3637 3717 3322 2850  151 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>age.for.grade<span class="ot">=</span>yrbs<span class="sc">$</span>age<span class="sc">-</span>yrbs<span class="sc">$</span>grade</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>age.for.grade, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>age.for.grade
   0    1    2    3    4    5    6    7    8    9 &lt;NA&gt; 
   7   14   16   34   93 6269 6572  472   30    4  166 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>appropriate.age.for.grade<span class="ot">=</span>yrbs<span class="sc">$</span>age.for.grade<span class="sc">&lt;=</span><span class="dv">6</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(appropriate.age.for.grade <span class="sc">~</span>age.for.grade, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         age.for.grade
appropriate.age.for.grade    0    1    2    3    4    5    6    7    8    9
                    TRUE     7   14   16   34   93 6269 6572    0    0    0
                    FALSE    0    0    0    0    0    0    0  472   30    4
                    &lt;NA&gt;     0    0    0    0    0    0    0    0    0    0
                         age.for.grade
appropriate.age.for.grade &lt;NA&gt;
                    TRUE     0
                    FALSE    0
                    &lt;NA&gt;   166</code></pre>
</div>
</div>
<p>Wearing a seatbelt never/rarely</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>rarely.seatbelt<span class="ot">=</span>yrbs<span class="sc">$</span>QN8<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(rarely.seatbelt <span class="sc">~</span> Q8 , <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Q8
rarely.seatbelt Never Rarely Sometimes Most of the time Always &lt;NA&gt;
          TRUE    294    495         0                0      0    0
          FALSE     0      0      1064             2999   6297    0
          &lt;NA&gt;      0      0         0                0      0 2528</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>msm <span class="ot">=</span> (yrbs<span class="sc">$</span>Q65<span class="sc">==</span><span class="st">"Males"</span> <span class="sc">&amp;</span> yrbs<span class="sc">$</span>female<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>wsw <span class="ot">=</span> (yrbs<span class="sc">$</span>Q65<span class="sc">==</span><span class="st">"Females"</span> <span class="sc">&amp;</span> yrbs<span class="sc">$</span>female<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>same.sex.only<span class="ot">=</span> ( yrbs<span class="sc">$</span>msm <span class="sc">|</span> yrbs<span class="sc">$</span>wsw )</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>same.sex<span class="ot">=</span> ( yrbs<span class="sc">$</span>same.sex.only <span class="sc">|</span> yrbs<span class="sc">$</span>Q65<span class="sc">==</span><span class="st">"Females and males"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(same.sex <span class="sc">~</span> Q65, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Q65
same.sex Never had sexual contact Females Males Females and males &lt;NA&gt;
   TRUE                         0     193    99               543    0
   FALSE                     4988    2642  2214                 0    0
   &lt;NA&gt;                         0      30    17                 0 2951</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>glb<span class="ot">=</span>yrbs<span class="sc">$</span>Q66<span class="sc">==</span><span class="st">"Gay or lesbian"</span> <span class="sc">|</span> yrbs<span class="sc">$</span>Q66<span class="sc">==</span><span class="st">"Bisexual"</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(glb <span class="sc">~</span> Q66, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Q66
glb     Heterosexual (straight) Gay or lesbian Bisexual Not sure  &lt;NA&gt;
  TRUE                        0            380     1151        0     0
  FALSE                   10853              0        0      591     0
  &lt;NA&gt;                        0              0        0        0   702</code></pre>
</div>
</div>
<p>We also think that sexual orientation could be related. Define variables for which sex respondents have had sex with (MSM = males who have sex with males, WSW = women who have sex with women), and their sexual orientation. Note that MSM/WSW variables are associated with the predictor of number of sexual partners, so it’s problematic to use them as covariates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>glbq<span class="ot">=</span>yrbs<span class="sc">$</span>Q66<span class="sc">==</span><span class="st">"Gay or lesbian"</span> <span class="sc">|</span> yrbs<span class="sc">$</span>Q66<span class="sc">==</span><span class="st">"Bisexual"</span> <span class="sc">|</span> yrbs<span class="sc">$</span>Q66<span class="sc">==</span><span class="st">"Not sure"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(glbq <span class="sc">~</span> Q66, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Q66
glbq    Heterosexual (straight) Gay or lesbian Bisexual Not sure  &lt;NA&gt;
  TRUE                        0            380     1151      591     0
  FALSE                   10853              0        0        0     0
  &lt;NA&gt;                        0              0        0        0   702</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>any.sports.team<span class="ot">=</span>yrbs<span class="sc">$</span>QN82<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(any.sports.team <span class="sc">~</span> Q82, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Q82
any.sports.team 0 teams 1 team 2 teams 3 or more teams &lt;NA&gt;
          TRUE        0   2584    1737            1224    0
          FALSE    4242      0       0               0    0
          &lt;NA&gt;        0      0       0               0 3890</code></pre>
</div>
</div>
</section>
</section>
<section id="strength-training-and-sexual-partners" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="strength-training-and-sexual-partners"><span class="header-section-number">13.3</span> Strength training and sexual partners</h2>
<p>Strength training and number of sexual partners Our main predictor and outcome variables are number of sexual partners and days of strength training.</p>
<section id="define-variables" class="level3" data-number="13.3.1">
<h3 data-number="13.3.1" class="anchored" data-anchor-id="define-variables"><span class="header-section-number">13.3.1</span> Define variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>num.partners<span class="ot">=</span><span class="fu">as.numeric</span>(yrbs<span class="sc">$</span>Q60) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(num.partners <span class="sc">~</span> Q60, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Q60
num.partners Never had sex 1 person 2 people 3 people 4 people 5 people
        0             7435        0        0        0        0        0
        1                0     2043        0        0        0        0
        2                0        0      926        0        0        0
        3                0        0        0      563        0        0
        4                0        0        0        0      294        0
        5                0        0        0        0        0      197
        6                0        0        0        0        0        0
        &lt;NA&gt;             0        0        0        0        0        0
            Q60
num.partners 6 or more people &lt;NA&gt;
        0                   0    0
        1                   0    0
        2                   0    0
        3                   0    0
        4                   0    0
        5                   0    0
        6                 501    0
        &lt;NA&gt;                0 1718</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>days.strength.training<span class="ot">=</span><span class="fu">as.numeric</span>(yrbs<span class="sc">$</span>Q95) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(Q95<span class="sc">~</span>days.strength.training, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        days.strength.training
Q95         0    1    2    3    4    5    6    7 &lt;NA&gt;
  0 days 2568    0    0    0    0    0    0    0    0
  1 day     0  812    0    0    0    0    0    0    0
  2 days    0    0  973    0    0    0    0    0    0
  3 days    0    0    0 1067    0    0    0    0    0
  4 days    0    0    0    0  763    0    0    0    0
  5 days    0    0    0    0    0  877    0    0    0
  6 days    0    0    0    0    0    0  361    0    0
  7 days    0    0    0    0    0    0    0 1053    0
  &lt;NA&gt;      0    0    0    0    0    0    0    0 5203</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>any.strength.training<span class="ot">=</span>yrbs<span class="sc">$</span>days.strength.training <span class="sc">&gt;=</span> <span class="dv">1</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(Q95<span class="sc">~</span>any.strength.training, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        any.strength.training
Q95      TRUE FALSE &lt;NA&gt;
  0 days    0  2568    0
  1 day   812     0    0
  2 days  973     0    0
  3 days 1067     0    0
  4 days  763     0    0
  5 days  877     0    0
  6 days  361     0    0
  7 days 1053     0    0
  &lt;NA&gt;      0     0 5203</code></pre>
</div>
</div>
</section>
<section id="crude-odds-ratio" class="level3" data-number="13.3.2">
<h3 data-number="13.3.2" class="anchored" data-anchor-id="crude-odds-ratio"><span class="header-section-number">13.3.2</span> Crude odds ratio</h3>
<p>Evaluate whether strength training is associated with number of sexual partners. The first model estimates the crude odds ratio and its p-value. The second model estimates the adjusted odds ratio, adjusting for age, gender, and sports team participation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>model0<span class="ot">=</span><span class="fu">glm</span>(any.strength.training <span class="sc">~</span> num.partners, <span class="at">family=</span><span class="st">"binomial"</span>, <span class="at">data=</span>yrbs)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model0)), <span class="fu">exp</span>(<span class="fu">confint</span>(model0)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                         2.5 %   97.5 %
(Intercept)  2.325748 2.197629 2.462291
num.partners 1.023808 0.991453 1.057742</code></pre>
</div>
</div>
</section>
<section id="adjusted-odds-ratio" class="level3" data-number="13.3.3">
<h3 data-number="13.3.3" class="anchored" data-anchor-id="adjusted-odds-ratio"><span class="header-section-number">13.3.3</span> Adjusted odds ratio</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>model1<span class="ot">=</span><span class="fu">glm</span>(any.strength.training <span class="sc">~</span> num.partners <span class="sc">+</span> age <span class="sc">+</span> female <span class="sc">+</span> any.sports.team <span class="sc">+</span> any.sports.team<span class="sc">*</span>female <span class="sc">+</span> glb <span class="sc">+</span> glb<span class="sc">*</span>female , <span class="at">family=</span><span class="st">"binomial"</span>, <span class="at">data=</span>yrbs)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model1, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = any.strength.training ~ num.partners + age + female + 
    any.sports.team + any.sports.team * female + glb + glb * 
    female, family = "binomial", data = yrbs)
                               coef.est coef.se z value Pr(&gt;|z|)
(Intercept)                     1.93     0.37    5.19    0.00   
num.partners                    0.03     0.02    1.72    0.08   
age                            -0.09     0.02   -3.92    0.00   
femaleTRUE                     -0.40     0.08   -5.19    0.00   
any.sports.teamTRUE             1.38     0.08   16.40    0.00   
glbTRUE                        -0.62     0.16   -3.77    0.00   
femaleTRUE:any.sports.teamTRUE -0.38     0.11   -3.44    0.00   
femaleTRUE:glbTRUE              0.34     0.19    1.80    0.07   
---
  n = 7433, k = 8
  residual deviance = 8312.0, null deviance = 9031.6 (difference = 719.6)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model1)),<span class="fu">exp</span>(<span class="fu">confint</span>(model1)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             2.5 %     97.5 %
(Intercept)                    6.9165709 3.3364304 14.3661158
num.partners                   1.0324601 0.9958725  1.0709013
age                            0.9139132 0.8736332  0.9559790
femaleTRUE                     0.6683446 0.5738147  0.7780850
any.sports.teamTRUE            3.9775010 3.3752060  4.6951738
glbTRUE                        0.5400348 0.3925578  0.7459683
femaleTRUE:any.sports.teamTRUE 0.6859657 0.5531117  0.8501359
femaleTRUE:glbTRUE             1.4015063 0.9693141  2.0204604</code></pre>
</div>
</div>
<p>The crude odds ratio and 95% confidence interval for the association between number of sexual partners and engaging in any strength training is 1.03 (1.01, 1.06), and the adjusted odds ratio is 1.04 (1.01, 1.07), adjusting for age, sex, sexual orientation, and sports team participation. We can regard the coefficients on these control variables as nuisance parameters. We can evaluate for effect modification by gender for both our main effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model2<span class="ot">=</span><span class="fu">glm</span>(any.strength.training <span class="sc">~</span> num.partners <span class="sc">+</span> age <span class="sc">+</span> female <span class="sc">+</span> any.sports.team <span class="sc">+</span> any.sports.team<span class="sc">*</span>female <span class="sc">+</span> glb <span class="sc">+</span> glb<span class="sc">*</span>female <span class="sc">+</span> num.partners<span class="sc">*</span>female, <span class="at">family=</span><span class="st">"binomial"</span>, <span class="at">data=</span>yrbs)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model2, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = any.strength.training ~ num.partners + age + female + 
    any.sports.team + any.sports.team * female + glb + glb * 
    female + num.partners * female, family = "binomial", data = yrbs)
                               coef.est coef.se z value Pr(&gt;|z|)
(Intercept)                     1.82     0.37    4.85    0.00   
num.partners                    0.09     0.03    3.46    0.00   
age                            -0.09     0.02   -3.73    0.00   
femaleTRUE                     -0.31     0.08   -3.67    0.00   
any.sports.teamTRUE             1.37     0.08   16.29    0.00   
glbTRUE                        -0.63     0.16   -3.85    0.00   
femaleTRUE:any.sports.teamTRUE -0.37     0.11   -3.40    0.00   
femaleTRUE:glbTRUE              0.37     0.19    1.99    0.05   
num.partners:femaleTRUE        -0.12     0.04   -3.29    0.00   
---
  n = 7433, k = 9
  residual deviance = 8301.0, null deviance = 9031.6 (difference = 730.6)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model2)),<span class="fu">exp</span>(<span class="fu">confint</span>(model2)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             2.5 %     97.5 %
(Intercept)                    6.1572718 2.9583529 12.8375392
num.partners                   1.0971433 1.0417864  1.1573405
age                            0.9175708 0.8770303  0.9599216
femaleTRUE                     0.7369965 0.6261359  0.8671537
any.sports.teamTRUE            3.9458993 3.3478580  4.6585373
glbTRUE                        0.5322496 0.3865827  0.7357501
femaleTRUE:any.sports.teamTRUE 0.6890158 0.5555495  0.8539527
femaleTRUE:glbTRUE             1.4537884 1.0042945  2.0984839
num.partners:femaleTRUE        0.8873172 0.8260548  0.9524688</code></pre>
</div>
</div>
<p>There is much effect modification, so we may prefer to create separate models for males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>model2f<span class="ot">=</span><span class="fu">glm</span>(any.strength.training <span class="sc">~</span> num.partners <span class="sc">+</span> age</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span> any.sports.team <span class="sc">+</span> glb , <span class="at">family=</span><span class="st">"binomial"</span>, <span class="at">data=</span>yrbs, <span class="at">subset=</span>female<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model2f, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = any.strength.training ~ num.partners + age + any.sports.team + 
    glb, family = "binomial", data = yrbs, subset = female == 
    1)
                    coef.est coef.se z value Pr(&gt;|z|)
(Intercept)          1.52     0.49    3.12    0.00   
num.partners        -0.03     0.03   -1.02    0.31   
age                 -0.09     0.03   -2.84    0.00   
any.sports.teamTRUE  1.00     0.07   14.18    0.00   
glbTRUE             -0.26     0.09   -2.80    0.01   
---
  n = 3839, k = 5
  residual deviance = 4743.0, null deviance = 4998.2 (difference = 255.2)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model2f)),<span class="fu">exp</span>(<span class="fu">confint</span>(model2f)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  2.5 %     97.5 %
(Intercept)         4.5913847 1.7612809 11.9864705
num.partners        0.9737004 0.9254261  1.0248685
age                 0.9168951 0.8635863  0.9734297
any.sports.teamTRUE 2.7183719 2.3681710  3.1225726
glbTRUE             0.7737496 0.6467414  0.9265395</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>model2m<span class="ot">=</span><span class="fu">glm</span>(any.strength.training <span class="sc">~</span> num.partners <span class="sc">+</span> age <span class="sc">+</span> any.sports.team <span class="sc">+</span> glb , <span class="at">family=</span><span class="st">"binomial"</span>, <span class="at">data=</span>yrbs, <span class="at">subset=</span>female<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model2m, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = any.strength.training ~ num.partners + age + any.sports.team + 
    glb, family = "binomial", data = yrbs, subset = female == 
    0)
                    coef.est coef.se z value Pr(&gt;|z|)
(Intercept)          1.80     0.57    3.18    0.00   
num.partners         0.09     0.03    3.40    0.00   
age                 -0.09     0.04   -2.42    0.02   
any.sports.teamTRUE  1.37     0.08   16.28    0.00   
glbTRUE             -0.63     0.16   -3.85    0.00   
---
  n = 3594, k = 5
  residual deviance = 3558.1, null deviance = 3896.5 (difference = 338.4)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model2m)), <span class="fu">exp</span>(<span class="fu">confint</span>(model2m)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  2.5 %     97.5 %
(Intercept)         6.0619916 2.0041506 18.4343083
num.partners        1.0969474 1.0407212  1.1581297
age                 0.9184637 0.8573032  0.9837506
any.sports.teamTRUE 3.9464675 3.3477291  4.6600102
glbTRUE             0.5322545 0.3865890  0.7357508</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>model1<span class="ot">=</span><span class="fu">glm</span>(num.partners <span class="sc">~</span> days.strength.training <span class="sc">+</span> female <span class="sc">+</span> age <span class="sc">+</span> any.sports.team <span class="sc">+</span> glb, <span class="at">data=</span>yrbs, <span class="at">family=</span>poisson)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = num.partners ~ days.strength.training + female + 
    age + any.sports.team + glb, family = poisson, data = yrbs)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.5304  -1.2333  -0.9343   0.3355   5.7570  

Coefficients:
                        Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)            -6.739015   0.180510 -37.333  &lt; 2e-16 ***
days.strength.training  0.045405   0.005272   8.613  &lt; 2e-16 ***
femaleTRUE             -0.201368   0.025778  -7.812 5.65e-15 ***
age                     0.399385   0.010645  37.517  &lt; 2e-16 ***
any.sports.teamTRUE     0.075070   0.026434   2.840  0.00451 ** 
glbTRUE                 0.366196   0.036621  10.000  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 15862  on 7432  degrees of freedom
Residual deviance: 14109  on 7427  degrees of freedom
  (6244 observations deleted due to missingness)
AIC: 21439

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
<section id="example-asthma-and-smoking" class="level3" data-number="13.3.4">
<h3 data-number="13.3.4" class="anchored" data-anchor-id="example-asthma-and-smoking"><span class="header-section-number">13.3.4</span> Example: asthma and smoking</h3>
<p>Asthma and smoking in the past month This analysis is based on a past student’s project, evaluating the association between asthma and smoking. The student wanted to evaluate whether males and females have different asso- ciations. They also thought that being older than the typical student in their grade may be a potential confounding factor. Here’s the start of an analysis.</p>
<p>Has a doctor or nurse ever told you that you have asthma?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>asthma<span class="ot">=</span>yrbs<span class="sc">$</span>Q87<span class="sc">==</span><span class="st">"Yes"</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(asthma <span class="sc">~</span> Q87, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Q87
asthma   Yes   No Not sure &lt;NA&gt;
  TRUE  2919    0        0    0
  FALSE    0 9354      627    0
  &lt;NA&gt;     0    0        0  777</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>pastmonth_smoking<span class="ot">=</span>yrbs<span class="sc">$</span>QN32<span class="sc">==</span><span class="dv">1</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(pastmonth_smoking <span class="sc">~</span> Q32, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Q32
pastmonth_smoking 0 days 1 or 2 days 3 to 5 days 6 to 9 days 10 to 19 days
            TRUE       0         327         114          55            71
            FALSE  11591           0           0           0             0
            &lt;NA&gt;       0           0           0           0             0
                 Q32
pastmonth_smoking 20 to 29 days All 30 days  &lt;NA&gt;
            TRUE             28         131     0
            FALSE             0           0     0
            &lt;NA&gt;              0           0  1360</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(asthma <span class="sc">~</span> pastmonth_smoking, <span class="at">data=</span>yrbs, <span class="at">useNA=</span><span class="st">"no"</span>, <span class="at">margins=</span>T, <span class="at">format=</span><span class="st">"percent"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       pastmonth_smoking
asthma       TRUE     FALSE
  TRUE   23.28358  22.23031
  FALSE  76.71642  77.76969
  Total 100.00000 100.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">tally</span>(asthma <span class="sc">~</span> pastmonth_smoking, <span class="at">data=</span>yrbs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tally(asthma ~ pastmonth_smoking, data = yrbs)
X-squared = 49.704, df = 4, p-value = 4.164e-10</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>model1<span class="ot">=</span><span class="fu">glm</span>(pastmonth_smoking <span class="sc">~</span> asthma, <span class="at">data=</span>yrbs, <span class="at">family=</span>binomial)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model1, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = pastmonth_smoking ~ asthma, family = binomial, 
    data = yrbs)
            coef.est coef.se z value Pr(&gt;|z|)
(Intercept)  -2.81     0.05  -61.91    0.00  
asthmaTRUE    0.06     0.09    0.64    0.52  
---
  n = 11664, k = 2
  residual deviance = 5128.7, null deviance = 5129.1 (difference = 0.4)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model1)),<span class="fu">exp</span>(<span class="fu">confint</span>(model1)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                            2.5 %    97.5 %
(Intercept) 0.06011696 0.05493165 0.0656376
asthmaTRUE  1.06176008 0.88020795 1.2739006</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>model2<span class="ot">=</span><span class="fu">glm</span>(pastmonth_smoking <span class="sc">~</span> asthma  <span class="sc">+</span> female <span class="sc">+</span>age <span class="sc">+</span> appropriate.age.for.grade, <span class="at">data=</span>yrbs, <span class="at">family=</span>binomial)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model2, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = pastmonth_smoking ~ asthma + female + age + appropriate.age.for.grade, 
    family = binomial, data = yrbs)
                              coef.est coef.se z value Pr(&gt;|z|)
(Intercept)                    -6.48     0.62  -10.48    0.00  
asthmaTRUE                      0.05     0.10    0.51    0.61  
femaleTRUE                     -0.36     0.08   -4.38    0.00  
age                             0.26     0.03    7.56    0.00  
appropriate.age.for.gradeTRUE  -0.43     0.18   -2.43    0.02  
---
  n = 11508, k = 5
  residual deviance = 4852.6, null deviance = 4947.7 (difference = 95.1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model2)),<span class="fu">exp</span>(<span class="fu">confint</span>(model2)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                 2.5 %      97.5 %
(Intercept)                   0.001526682 0.0004512483 0.005104352
asthmaTRUE                    1.050394219 0.8656139433 1.267371207
femaleTRUE                    0.696714307 0.5922142934 0.818723249
age                           1.298936427 1.2140637435 1.390404241
appropriate.age.for.gradeTRUE 0.652620488 0.4678269198 0.933971235</code></pre>
</div>
</div>
<ol type="1">
<li><p>How do you interpret the bivariate results? Which direction would you report?</p></li>
<li><p>How would you report and interpret the crude odds ratio?</p></li>
<li><p>How would you report and interpret the adjusted odds ratio?</p></li>
<li><p>What information would you put into a table of the logistic regression results?</p></li>
</ol>
</section>
<section id="example-suicidal-ideation-and-grades-in-school" class="level3" data-number="13.3.5">
<h3 data-number="13.3.5" class="anchored" data-anchor-id="example-suicidal-ideation-and-grades-in-school"><span class="header-section-number">13.3.5</span> Example: suicidal ideation and grades in school</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>suicidal.ideation<span class="ot">=</span>yrbs<span class="sc">$</span>Q26<span class="sc">==</span><span class="st">"Yes"</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(suicidal.ideation <span class="sc">~</span> Q26, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Q26
suicidal.ideation   Yes    No  &lt;NA&gt;
            TRUE   2633     0     0
            FALSE     0 10804     0
            &lt;NA&gt;      0     0   240</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>yrbs<span class="sc">$</span>grades<span class="ot">=</span>yrbs<span class="sc">$</span>Q89</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(grades <span class="sc">~</span> Q89, <span class="at">data=</span>yrbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Q89
grades                 Mostly A's Mostly B's Mostly C's Mostly D's Mostly F's
  Mostly A's                 5130          0          0          0          0
  Mostly B's                    0       4655          0          0          0
  Mostly C's                    0          0       2068          0          0
  Mostly D's                    0          0          0        435          0
  Mostly F's                    0          0          0          0        174
  None of these grades          0          0          0          0          0
  Not sure                      0          0          0          0          0
  &lt;NA&gt;                          0          0          0          0          0
                      Q89
grades                 None of these grades Not sure &lt;NA&gt;
  Mostly A's                              0        0    0
  Mostly B's                              0        0    0
  Mostly C's                              0        0    0
  Mostly D's                              0        0    0
  Mostly F's                              0        0    0
  None of these grades                  102        0    0
  Not sure                                0      447    0
  &lt;NA&gt;                                    0        0  666</code></pre>
</div>
</div>
<p>is.na(yrbs<span class="math inline">\(grades) = yrbs\)</span>Q89==“None of these grades”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(suicidal.ideation <span class="sc">~</span> grades, <span class="at">data=</span>yrbs, <span class="at">format=</span><span class="st">"percent"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 grades
suicidal.ideation Mostly A's Mostly B's Mostly C's Mostly D's Mostly F's
            TRUE   15.828460  20.107411  22.147002  30.344828  39.655172
            FALSE  83.099415  78.625134  75.628627  65.057471  54.022989
            &lt;NA&gt;    1.072125   1.267454   2.224371   4.597701   6.321839
                 grades
suicidal.ideation None of these grades  Not sure      &lt;NA&gt;
            TRUE             17.647059 23.042506 15.765766
            FALSE            80.392157 72.483221 80.180180
            &lt;NA&gt;              1.960784  4.474273  4.054054</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">tally</span>(suicidal.ideation <span class="sc">~</span> grades, <span class="at">data=</span>yrbs, <span class="at">format=</span><span class="st">"percent"</span>)[<span class="dv">1</span>,],</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">type=</span><span class="st">"b"</span>, <span class="at">ylab=</span><span class="st">"Percent with suicidal ideation"</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">axes=</span>F, <span class="at">xlab=</span><span class="st">"Grades in school"</span>)</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>)</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"As"</span>, <span class="st">"Bs"</span>, <span class="st">"Cs"</span>, <span class="st">"Ds"</span>, <span class="st">"Fs"</span>, <span class="st">"None"</span>, <span class="st">"Unsure"</span>, <span class="st">"Missing"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt11_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>model1<span class="ot">=</span><span class="fu">glm</span>(suicidal.ideation <span class="sc">~</span> grades, <span class="at">data=</span>yrbs, <span class="at">family=</span>binomial)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model1, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = suicidal.ideation ~ grades, family = binomial, 
    data = yrbs)
                           coef.est coef.se z value Pr(&gt;|z|)
(Intercept)                 -1.66     0.04  -43.31    0.00  
gradesMostly B's             0.29     0.05    5.56    0.00  
gradesMostly C's             0.43     0.07    6.57    0.00  
gradesMostly D's             0.90     0.11    7.99    0.00  
gradesMostly F's             1.35     0.16    8.27    0.00  
gradesNone of these grades   0.14     0.26    0.54    0.59  
gradesNot sure               0.51     0.12    4.29    0.00  
---
  n = 12798, k = 7
  residual deviance = 12579.5, null deviance = 12720.2 (difference = 140.7)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model1)),<span class="fu">exp</span>(<span class="fu">confint</span>(model1)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         2.5 %    97.5 %
(Intercept)                0.1904762 0.1765901 0.2051917
gradesMostly B's           1.3426230 1.2102757 1.4897116
gradesMostly C's           1.5374041 1.3515868 1.7472525
gradesMostly D's           2.4487633 1.9608995 3.0444650
gradesMostly F's           3.8537234 2.7912908 5.2960478
gradesNone of these grades 1.1524390 0.6674814 1.8838241
gradesNot sure             1.6689815 1.3154428 2.1017143</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>model2<span class="ot">=</span><span class="fu">glm</span>(suicidal.ideation <span class="sc">~</span> grades <span class="sc">+</span> female <span class="sc">+</span> age<span class="sc">+</span> appropriate.age.for.grade, <span class="at">data=</span>yrbs, <span class="at">family=</span>binomial)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(model2, <span class="at">detail=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm(formula = suicidal.ideation ~ grades + female + age + appropriate.age.for.grade, 
    family = binomial, data = yrbs)
                              coef.est coef.se z value Pr(&gt;|z|)
(Intercept)                   -1.84     0.35   -5.31    0.00   
gradesMostly B's               0.37     0.05    6.77    0.00   
gradesMostly C's               0.59     0.07    8.72    0.00   
gradesMostly D's               1.12     0.12    9.60    0.00   
gradesMostly F's               1.55     0.17    8.97    0.00   
gradesNone of these grades     0.22     0.27    0.80    0.42   
gradesNot sure                 0.61     0.12    4.91    0.00   
femaleTRUE                     0.82     0.05   17.07    0.00   
age                           -0.02     0.02   -1.12    0.26   
appropriate.age.for.gradeTRUE -0.02     0.12   -0.18    0.86   
---
  n = 12620, k = 10
  residual deviance = 12037.4, null deviance = 12479.0 (difference = 441.5)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model2)),<span class="fu">exp</span>(<span class="fu">confint</span>(model2)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             2.5 %    97.5 %
(Intercept)                   0.1581005 0.07991345 0.3121621
gradesMostly B's              1.4441552 1.29852010 1.6064646
gradesMostly C's              1.8063832 1.58092905 2.0624705
gradesMostly D's              3.0648026 2.43263882 3.8452151
gradesMostly F's              4.7252419 3.35433489 6.6221255
gradesNone of these grades    1.2456981 0.70576743 2.0777164
gradesNot sure                1.8403320 1.43659949 2.3397027
femaleTRUE                    2.2726675 2.06895397 2.4981077
age                           0.9789436 0.94324871 1.0159705
appropriate.age.for.gradeTRUE 0.9779215 0.76959328 1.2544318</code></pre>
</div>
</div>
<ol type="1">
<li>How do you report the bivariate results?</li>
<li>How would you report and interpret the crude odds ratio(s)?</li>
<li>How would you report and interpret the adjusted odds ratio(s)?</li>
<li>What information would you put into a table of the logistic regression results?</li>
</ol>
<p>For a visual data display (not necessary for the project), you can display the multivariate results visually as adjusted odds ratios with or without confidence intervals. Andrew Gelman calls the data display “the secret weapon.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model2))[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], <span class="at">ylab=</span><span class="st">"OR"</span>, <span class="at">type=</span><span class="st">"b"</span>, <span class="at">axes=</span>F, <span class="at">xlab=</span><span class="st">"Grades"</span>,</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>))</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>)</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Mostly Bs"</span>, <span class="st">"Mostly Cs"</span>, <span class="st">"Mostly Ds"</span>, <span class="st">"Mostly Fs"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt11_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To show the confidence intervals, we need another library, and we put the confidence intervals into a new variable to save on computational time. It may be helpful context to tell the viewer how many participants are in each category. The symbol n tells R to insert a new line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gplots)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>ci<span class="ot">=</span><span class="fu">exp</span>(<span class="fu">confint</span>(model2))</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plotCI</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model2))[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], <span class="at">li=</span>ci[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span>], <span class="at">ui=</span>ci[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">2</span>], <span class="at">ylab=</span><span class="st">"OR"</span>, <span class="at">type=</span><span class="st">"b"</span>,</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">axes=</span>F, <span class="at">xlab=</span><span class="st">"Grades"</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>), <span class="at">pch=</span><span class="dv">20</span>, <span class="at">gap=</span><span class="dv">0</span>)</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>)</span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Mostly Bs</span><span class="sc">\n</span><span class="st">(n=5660)"</span>, <span class="st">"Mostly Cs</span><span class="sc">\n</span><span class="st">(n=3031)"</span>,</span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a><span class="st">"Mostly Ds</span><span class="sc">\n</span><span class="st">(n=563)"</span>, <span class="st">"Mostly Fs</span><span class="sc">\n</span><span class="st">(n=245)"</span>), <span class="at">tick=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt11_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>How do you interpret these findings? Is it more likely that poor grades cause suicidal ideation, that suicidal ideation causes poor grades, or that a third variable is responsible?</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapt10.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Ecological studies</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapt12.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Survey data analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>