<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Epidemiology Methods lecture notes - 3&nbsp; Data displays</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapt2.html" rel="next">
<link href="./chaptA.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data displays</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Epidemiology Methods lecture notes</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction: Types of studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chaptA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt1.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data displays</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Identifying research questions and data sources</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Testing hypotheses</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Associations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt5.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Causality vs association</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt6.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Excess risk</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt7.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Measurement error and screening</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt8.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confounding and linear regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt9.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Confounding and causal graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt10.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Ecological studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt11.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Example data analysis in YRBS</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt12.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Survey data analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt13.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Randomized experiments and quasi-experiments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt14.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cohort studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapt15.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Case-control studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#plots-as-necessary-data-summaries" id="toc-plots-as-necessary-data-summaries" class="nav-link active" data-scroll-target="#plots-as-necessary-data-summaries"><span class="toc-section-number">3.1</span>  Plots as necessary data summaries</a></li>
  <li><a href="#effective-presentation-of-data" id="toc-effective-presentation-of-data" class="nav-link" data-scroll-target="#effective-presentation-of-data"><span class="toc-section-number">3.2</span>  Effective presentation of data</a></li>
  <li><a href="#choosing-suitable-plots-and-analyses-for-the-data" id="toc-choosing-suitable-plots-and-analyses-for-the-data" class="nav-link" data-scroll-target="#choosing-suitable-plots-and-analyses-for-the-data"><span class="toc-section-number">3.3</span>  Choosing suitable plots and analyses for the data</a></li>
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise"><span class="toc-section-number">3.4</span>  Exercise</a></li>
  <li><a href="#visualizing-a-screening-test" id="toc-visualizing-a-screening-test" class="nav-link" data-scroll-target="#visualizing-a-screening-test"><span class="toc-section-number">3.5</span>  Visualizing a screening test</a></li>
  <li><a href="#data-displays-in-r" id="toc-data-displays-in-r" class="nav-link" data-scroll-target="#data-displays-in-r"><span class="toc-section-number">3.6</span>  Data displays in R</a></li>
  <li><a href="#exploring-a-dataset" id="toc-exploring-a-dataset" class="nav-link" data-scroll-target="#exploring-a-dataset"><span class="toc-section-number">3.7</span>  Exploring a dataset</a></li>
  <li><a href="#single-variable-plots" id="toc-single-variable-plots" class="nav-link" data-scroll-target="#single-variable-plots"><span class="toc-section-number">3.8</span>  Single variable plots</a></li>
  <li><a href="#two-variable-plots" id="toc-two-variable-plots" class="nav-link" data-scroll-target="#two-variable-plots"><span class="toc-section-number">3.9</span>  Two variable plots</a></li>
  <li><a href="#stratifying-plots-by-a-third-variable" id="toc-stratifying-plots-by-a-third-variable" class="nav-link" data-scroll-target="#stratifying-plots-by-a-third-variable"><span class="toc-section-number">3.10</span>  Stratifying plots by a third variable</a></li>
  <li><a href="#making-historical-plots-in-r" id="toc-making-historical-plots-in-r" class="nav-link" data-scroll-target="#making-historical-plots-in-r"><span class="toc-section-number">3.11</span>  Making historical plots in R</a></li>
  <li><a href="#john-snows-cholera-data" id="toc-john-snows-cholera-data" class="nav-link" data-scroll-target="#john-snows-cholera-data"><span class="toc-section-number">3.12</span>  John Snow’s cholera data</a>
  <ul class="collapse">
  <li><a href="#questions-for-discussion" id="toc-questions-for-discussion" class="nav-link" data-scroll-target="#questions-for-discussion"><span class="toc-section-number">3.12.1</span>  Questions for discussion:</a></li>
  </ul></li>
  <li><a href="#florence-nightingales-data" id="toc-florence-nightingales-data" class="nav-link" data-scroll-target="#florence-nightingales-data"><span class="toc-section-number">3.13</span>  Florence Nightingale’s data</a></li>
  <li><a href="#births-by-day-of-year" id="toc-births-by-day-of-year" class="nav-link" data-scroll-target="#births-by-day-of-year"><span class="toc-section-number">3.14</span>  Births by day of year</a></li>
  <li><a href="#womens-weights-and-heights" id="toc-womens-weights-and-heights" class="nav-link" data-scroll-target="#womens-weights-and-heights"><span class="toc-section-number">3.15</span>  Women’s weights and heights</a></li>
  <li><a href="#esophageal-cancer-case-control-data" id="toc-esophageal-cancer-case-control-data" class="nav-link" data-scroll-target="#esophageal-cancer-case-control-data"><span class="toc-section-number">3.16</span>  Esophageal cancer case-control data</a></li>
  <li><a href="#map-data" id="toc-map-data" class="nav-link" data-scroll-target="#map-data"><span class="toc-section-number">3.17</span>  Map data</a></li>
  <li><a href="#summarizing-data-in-r" id="toc-summarizing-data-in-r" class="nav-link" data-scroll-target="#summarizing-data-in-r"><span class="toc-section-number">3.18</span>  Summarizing data in R</a></li>
  <li><a href="#data-are-data-frames" id="toc-data-are-data-frames" class="nav-link" data-scroll-target="#data-are-data-frames"><span class="toc-section-number">3.19</span>  Data are data frames</a>
  <ul class="collapse">
  <li><a href="#numerical-summaries-one-categorical-and-one-quantitative-variable" id="toc-numerical-summaries-one-categorical-and-one-quantitative-variable" class="nav-link" data-scroll-target="#numerical-summaries-one-categorical-and-one-quantitative-variable"><span class="toc-section-number">3.19.1</span>  Numerical summaries: one categorical and one quantitative variable</a></li>
  </ul></li>
  <li><a href="#tables-in-r-two-categorical-variables" id="toc-tables-in-r-two-categorical-variables" class="nav-link" data-scroll-target="#tables-in-r-two-categorical-variables"><span class="toc-section-number">3.20</span>  Tables in R: two categorical variables</a>
  <ul class="collapse">
  <li><a href="#analyzing-data-in-tables" id="toc-analyzing-data-in-tables" class="nav-link" data-scroll-target="#analyzing-data-in-tables"><span class="toc-section-number">3.20.1</span>  Analyzing data in tables</a></li>
  </ul></li>
  <li><a href="#two-continuous-variables" id="toc-two-continuous-variables" class="nav-link" data-scroll-target="#two-continuous-variables"><span class="toc-section-number">3.21</span>  Two continuous variables</a>
  <ul class="collapse">
  <li><a href="#r-data-object-manipulation-apply" id="toc-r-data-object-manipulation-apply" class="nav-link" data-scroll-target="#r-data-object-manipulation-apply"><span class="toc-section-number">3.21.1</span>  R data object manipulation: apply</a></li>
  </ul></li>
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1"><span class="toc-section-number">3.22</span>  Exercise</a>
  <ul class="collapse">
  <li><a href="#suggested-answers" id="toc-suggested-answers" class="nav-link" data-scroll-target="#suggested-answers"><span class="toc-section-number">3.22.1</span>  Suggested answers</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data displays</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Extra reading: Edward Tufte, The Visual Display of Quantitative Information (1983, 2001), 106–121. http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=00040Z</p>
<section id="plots-as-necessary-data-summaries" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="plots-as-necessary-data-summaries"><span class="header-section-number">3.1</span> Plots as necessary data summaries</h2>
<p>The following data — Anscombe’s quartet — have the same summary statistics (moments.) Plotting reveals the relationship between the factors. (Anscombe, F. J. (1973). Graphs in Statistical Analysis. American Statistician 27 (1): 17–21. Plots from wikipedia.)</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean of x</td>
<td style="text-align: left;">9 (exactly)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variance of x</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean of y</td>
<td style="text-align: left;">7.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variance of y</td>
<td style="text-align: left;">4.122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cor(x, y)</td>
<td style="text-align: left;">0.816</td>
</tr>
<tr class="even">
<td style="text-align: left;">Linear regression result</td>
<td style="text-align: left;">y = 3.00 + 0.500x</td>
</tr>
</tbody>
</table>
<p>Here are code that generate plots of Anscombe’s quartet. I place them one by one on a grid.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>p1<span class="ot">=</span><span class="fu">xyplot</span>(y1 <span class="sc">~</span> x1, <span class="at">data=</span>anscombe, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>p2<span class="ot">=</span><span class="fu">xyplot</span>(y2 <span class="sc">~</span> x2, <span class="at">data=</span>anscombe, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>p3<span class="ot">=</span><span class="fu">xyplot</span>(y3 <span class="sc">~</span> x3, <span class="at">data=</span>anscombe, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>p4<span class="ot">=</span><span class="fu">xyplot</span>(y4 <span class="sc">~</span> x4, <span class="at">data=</span>anscombe, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p1, <span class="at">pos =</span> <span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>), <span class="at">more =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p2, <span class="at">pos =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">1.0</span>), <span class="at">more =</span> T)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p3, <span class="at">pos =</span> <span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.0</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>), <span class="at">more =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p4, <span class="at">pos =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">0.5</span>), <span class="at">more =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Someone who gets a dataset may generate numerical summaries and linear regressions without looking at the data. You can see here that only the first dataset is appropriate for linear regression.</p>
<p>Dataset 2 needs a quadratic term to fit the parabolic shape.</p>
<p>Dataset 3 has a linear relationship but one large outlier that has a lot of leverage, pulling the regression line up.</p>
<p>Dataset 4 has no relationship at all between x and y. The line goes between the average value of the y at x4=8 and the datapoint at the far end: the regression line is a line determined by two points.</p>
</section>
<section id="effective-presentation-of-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="effective-presentation-of-data"><span class="header-section-number">3.2</span> Effective presentation of data</h2>
<ul>
<li><p>Use a plot rather than a table whenever possible.</p></li>
<li><p>White backgrounds and sans serif fonts are easier to read. (These are defaults in R.)</p></li>
<li><p>Maximize data to ink ratio: all ink should communicate something. If ink can be removed without losing information, it is “chart junk” and unnecessary.</p></li>
<li><p>Examples of unnecessary ink: unnecessary 3d plots, pie charts, “ducks.” A “duck” is an element of a plot that is only for decoration. Ducks are named after the Big Duck, located in Flanders, NY.</p></li>
</ul>
<p>The primary rule for data display is the less ink, the better. Eliminate as much as possible from a plot or table to avoid obscuring your data with extra ink or redundant information. This rule has a few consequences:</p>
<ul>
<li><p>Avoid graphical features that add ink without communicating anything, common in Excel.</p></li>
<li><p>Avoid pie charts and other plotting methods that communicate little information for the amount of ink used.</p></li>
</ul>
<p>R has a function pie to make a pie chart, but the help file helpfully notes that pie charts are terrible. “Pie charts are a very bad way of displaying information. The eye is good at judging linear measures and bad at judging relative areas. A bar chart or dot chart is a preferable way of displaying this type of data. Cleveland (1985), page 264:”Data that can be shown by pie charts always can be shown by a dot chart. This means that judgements of position along a common scale can be made instead of the less accurate angle judgements.” This statement is based on the empirical investigations of Cleveland and McGill as well as investigations by perceptual psychologists.”</p>
<p>You can make a pie chart to show Pacman, however.</p>
<p>Pacman in base R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="fu">c</span>(<span class="st">"Pacman"</span> <span class="ot">=</span> <span class="dv">78</span>, <span class="st">"Pacman's mouth"</span> <span class="ot">=</span> <span class="dv">22</span>),</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">init.angle =</span> <span class="dv">45</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"yellow"</span>, <span class="st">"white"</span>), <span class="at">border =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Pacman in ggplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">c</span>(<span class="st">"does not resemble Pacman"</span>, <span class="st">"resembles Pacman"</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">80</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> value, <span class="at">fill =</span> variable)) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"white"</span>, <span class="st">"yellow"</span>)) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="st">"y"</span>, <span class="at">start =</span> <span class="dv">2</span><span class="sc">*</span>pi<span class="sc">/</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Pac man"</span>) <span class="sc">+</span> </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Pyramid pie chart:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="fu">c</span>(<span class="at">Sky =</span> <span class="dv">78</span>, <span class="st">"Sunny side of pyramid"</span> <span class="ot">=</span> <span class="dv">17</span>, <span class="st">"Shady side of pyramid"</span> <span class="ot">=</span> <span class="dv">5</span>),</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">init.angle =</span> <span class="dv">315</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"deepskyblue"</span>, <span class="st">"yellow"</span>, <span class="st">"yellow3"</span>), <span class="at">border =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="choosing-suitable-plots-and-analyses-for-the-data" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="choosing-suitable-plots-and-analyses-for-the-data"><span class="header-section-number">3.3</span> Choosing suitable plots and analyses for the data</h2>
<p>We divide data into categorical (C) and quantitative (Q). The types of analysis depend on the types of data.</p>
<p>Categorical variables can further be categorized as ordinal or non-ordinal.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable type</th>
<th style="text-align: left;">Outcome Quantitative</th>
<th style="text-align: left;">Outcome Categorical</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Predictor quantitative</td>
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow Q\)</span></td>
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow C\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Predictor categorical</td>
<td style="text-align: left;"><span class="math inline">\(C \rightarrow Q\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C \rightarrow C\)</span></td>
</tr>
</tbody>
</table>
<p>The displays and analysis types are not meant to correspond to each other.</p>
<p>This table is not meant to be a cookbook. This table demonstrates that some types of analysis definitely do not make sense for some types of data. E.g., scatterplot cannot be used instead of 2x2 table.</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 47%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Data</th>
<th style="text-align: left;">Display</th>
<th style="text-align: left;">Analysis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow Q\)</span></td>
<td style="text-align: left;">scatterplots (xyplot)</td>
<td style="text-align: left;">linear regression (lm)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(Q \rightarrow C\)</span> or <span class="math inline">\(C \rightarrow Q\)</span></td>
<td style="text-align: left;">Box and whisker plot (bwplot)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">dotplot (w or w/o confidence interval)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Categorical variable is binary</td>
<td style="text-align: left;">stratified density plot (densityplot)</td>
<td style="text-align: left;">t-test, Wilcoxon</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Categorical variable is binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Logistic regression glm( , family=binomial)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Categorical variable is not binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">test for trend (if ordinal): e.g., Cuzick’s</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Categorical variable is not binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Tukey’s HSD (anova followesd by TukeyHSD)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Categorical variable is not binary</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">transform to binary and use above methods</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(C \rightarrow C\)</span></td>
<td style="text-align: left;">Contingency table (tally)</td>
<td style="text-align: left;">chi-square test (chisq.test)</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Kruskal-Wallis test (kruskal.test)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">pairwise chi-square test</td>
</tr>
</tbody>
</table>
</section>
<section id="exercise" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="exercise"><span class="header-section-number">3.4</span> Exercise</h2>
<p>How can you improve the following plots?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://imageio.forbes.com/blogs-images/erikaandersen/files/2012/03/w1467103173.jpg?format=jpg&amp;width=560"><img src="https://imageio.forbes.com/blogs-images/erikaandersen/files/2012/03/w1467103173.jpg?format=jpg&amp;width=560" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Pirates and global warming (Source: Forbes (https://www.forbes.com/sites/erikaandersen/2012/03/23/true-fact-the-lack-of-pirates-is-causing-global-warming); Wikimedia commons.)</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/badplot-cottera.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Source: “Hematocrit was not validated as a surrogate end point for survival among epoetin-treated hemodialysis patients”, Dennis J. Cotter, Kevin Stefanik, Yi Zhang, Mae Thamer, Daniel Scharfstein, James Kaufman, Journal of Clinical Epidemiology 57(10):1086-1095, October 2004.</figcaption><p></p>
</figure>
</div>
<p>Source: Cotter DJ, et al.&nbsp;(2004) Hematocrit was not validated as a surrogate endpoint for survival amoung epoetin-treated hemodialysis patients. Journal of Clinical Epidemiology 57:1086-1095,</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/badplot-roedera.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Source: Roeder K (1994) DNA fingerprinting: A review of the controversy (with discussion). Statistical Science 9:222-278, Figure 4b</figcaption><p></p>
</figure>
</div>
<p>Source: Roeder K (1994) DNA fingerprinting: A review of the controversy (with discussion). Statistical Science 9:222-278, Figure 4b</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/inflation-fed-chair-height.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Height of fed chair and inflation rate.</figcaption><p></p>
</figure>
</div>
<p>\</p>
<p>Including an image of the fed chair is a ``duck’’ — if they are really making a point about the height of the chair of the Federal Reserve Board, they don’t need the picture. For an infographic (non-academic purpose), it is reasonable to include some eye-catching elements.</p>
</section>
<section id="visualizing-a-screening-test" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="visualizing-a-screening-test"><span class="header-section-number">3.5</span> Visualizing a screening test</h2>
<p>These hypothetical data show the results of a screening test for a low-prevalence condition.</p>
<p>Here are three visualizations of the screening test results. Is any more effective?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/screentest-fig1.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Screening test illustration</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/screentest-fig4.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Screening test for rare condition (Yes = red, No = blue), FN= false negative (outline red), TP = true positive (shaded red), FP = false positive (blue), and TN = true negative (outline blue).</figcaption><p></p>
</figure>
</div>
<p>For a higher prevalence condition, the data might look like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/screening-test-visualization-01.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Screening test for common condition</figcaption><p></p>
</figure>
</div>
<p>Is there a universally preferred method of displaying these data, or does it depend on context?</p>
<p>(Source: Tim Brock, How to explain screening test outcomes, <em>Significance</em>, 27 April 2017. Retrieved from: https://www.significancemagazine.com/science/547-a-visual-guide-to-screening-test-results)</p>
</section>
<section id="data-displays-in-r" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="data-displays-in-r"><span class="header-section-number">3.6</span> Data displays in R</h2>
<p>R is a free open-source statistical package that was first released in 1995, based on the S statistical package which was a commercial package developed at Bell Labs. R comprises a central set of commands augmented by libraries that introduce new commands.</p>
<p>Base R includes a plot command that provides for many types of plotting. as well as additional commands: histogram, barplot, dotchart, boxplot, and curve. These commands can get a bit involved. For example, putting two plots on the same axes requires specifying the scale for both plots, and in between putting the command par(new=T): three commands. Adding a regression line requires doing the regression and then giving the command abline: again, three commands.</p>
<p>In recent years, the ggplot has become a popular way to do plots. ggplot can be powerful, but it can be involved.</p>
<p>We use the package mosaic, which simplifies commands for statistics students. What would normally take 3 commands in regular R can be done in just 1 command. The plotting commands in Mosaic are listed in the R reference guide at the end of today’s notes. Mosaic is based on the lattice graphics package, something you may see referenced in the help pages.</p>
<p>Plotting commands in Mosaic use the same format:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">command</span> ( y \(\sim\) x, <span class="at">data=</span>dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can stratify by a third variable using simple variations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">command</span> ( y \(\sim\) x, <span class="at">groups=</span>z, <span class="at">data=</span>dataset)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">command</span> ( y \(\sim\) x <span class="sc">|</span> z, <span class="at">data=</span>dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploring-a-dataset" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="exploring-a-dataset"><span class="header-section-number">3.7</span> Exploring a dataset</h2>
<p>Many packages, including Mosaic, comes with built-in datasets that can be used for analysis. You can read about a built-in dataset using the help command (equivalent to a ?), and see the variables available using the names command.</p>
<p>We will use the HELPrct study (Health Evaluation and Linkage to Primary Care). ``The HELP study was a clinical trial for adult inpatients recruited from a detoxification unit. Patients with no primary care physician were randomized to receive a multidisciplinary assessment and a brief motivational intervention or usual care, with the goal of linking them to primary medical care.’’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(HELPrct)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="single-variable-plots" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="single-variable-plots"><span class="header-section-number">3.8</span> Single variable plots</h2>
<p>When there’s one variable, it is on the right side of the formula.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(<span class="sc">~</span>age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">densityplot</span>(<span class="sc">~</span>age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freqpolygon</span>(<span class="sc">~</span>age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(<span class="sc">~</span>age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bargraph</span>(<span class="sc">~</span>age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="two-variable-plots" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="two-variable-plots"><span class="header-section-number">3.9</span> Two variable plots</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(i1 <span class="sc">~</span> age, <span class="at">data=</span>HELPrct, <span class="at">ylab=</span><span class="st">"Number of drinks per day"</span>, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(age <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(substance <span class="sc">~</span> age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="stratifying-plots-by-a-third-variable" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="stratifying-plots-by-a-third-variable"><span class="header-section-number">3.10</span> Stratifying plots by a third variable</h2>
<p>Often it’s useful to stratify plots by a third variable. You can do this using two methods.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(i1 <span class="sc">~</span> age, <span class="at">groups=</span>female, <span class="at">data=</span>HELPrct, <span class="at">ylab=</span><span class="st">"Number of drinks per day"</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="at">auto.key=</span>T, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"p"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(i1 <span class="sc">~</span> age <span class="sc">|</span> female, <span class="at">data=</span>HELPrct, <span class="at">ylab=</span><span class="st">"Number of drinks per day"</span>, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="at">auto.key=</span>T, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"p"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="making-historical-plots-in-r" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="making-historical-plots-in-r"><span class="header-section-number">3.11</span> Making historical plots in R</h2>
</section>
<section id="john-snows-cholera-data" class="level2" data-number="3.12">
<h2 data-number="3.12" class="anchored" data-anchor-id="john-snows-cholera-data"><span class="header-section-number">3.12</span> John Snow’s cholera data</h2>
<p>John Snow’s cholera data is in the library HistData.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HistData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'HistData'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:mosaicData':

    Galton</code></pre>
</div>
</div>
<p>Number of cholera deaths by population size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(cholera_deaths <span class="sc">~</span> popn, <span class="at">data=</span>Cholera, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"p"</span>), </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab=</span><span class="st">"Population in 1849"</span>, <span class="at">ylab=</span><span class="st">"Number of cholera deaths in 1849"</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">main=</span><span class="st">"Cholera deaths in 1849"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(cholera_deaths <span class="sc">~</span> popn, <span class="at">groups=</span> water, <span class="at">auto.key=</span>T, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data=</span>Cholera, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"p"</span>), <span class="at">xlab=</span><span class="st">"Population in 1849"</span>, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab=</span><span class="st">"Number of cholera deaths in 1849"</span>, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">main=</span><span class="st">"Cholera deaths in 1849 by water supplier"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(cholera_deaths <span class="sc">~</span> popn <span class="sc">|</span> water, <span class="at">data=</span>Cholera, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">"Population in 1849"</span>, <span class="at">ylab=</span><span class="st">"Number of cholera deaths in 1849"</span> , </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">"Cholera deaths in 1849 by water supplier"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Number of cholera deaths by population density.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(cholera_deaths <span class="sc">~</span> pop_dens, <span class="at">data=</span>Cholera, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"p"</span>), </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab=</span><span class="st">"Population density in 1849"</span>, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab=</span><span class="st">"Number of cholera deaths in 1849"</span>, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">main=</span><span class="st">"Cholera deaths in 1849"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(cholera_deaths <span class="sc">~</span> pop_dens, <span class="at">groups=</span> water, <span class="at">data=</span>Cholera, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">type=</span><span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"p"</span>), <span class="at">auto.key=</span>T,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab=</span><span class="st">"Population density in 1849"</span>, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab=</span><span class="st">"Number of cholera deaths in 1849"</span>, </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">main=</span><span class="st">"Cholera deaths in 1849 by water supplier"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(cholera_deaths <span class="sc">~</span> pop_dens <span class="sc">|</span> water, <span class="at">data=</span>Cholera, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>),</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">"Population density in 1849 (persons per acre)"</span>, <span class="at">ylab=</span><span class="st">"Number of cholera deaths in 1849"</span> , </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">"Cholera deaths in 1849 by water supplier"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Number of cholera deaths by house value</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(cholera_deaths <span class="sc">~</span> house_valpp <span class="sc">|</span> water, <span class="at">data=</span>Cholera, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>),</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">"Average value of houses in 1849 (pounds)"</span>, <span class="at">ylab=</span><span class="st">"Number of cholera deaths in 1849"</span> , </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">"Cholera deaths in 1849 by water supplier"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="questions-for-discussion" class="level3" data-number="3.12.1">
<h3 data-number="3.12.1" class="anchored" data-anchor-id="questions-for-discussion"><span class="header-section-number">3.12.1</span> Questions for discussion:</h3>
<ul>
<li><p>Interpret each of these plots. Based on these plots, which factors predict cholera?</p></li>
<li><p>If you are able to explore the data further, are there other factors that appear important?</p></li>
</ul>
</section>
</section>
<section id="florence-nightingales-data" class="level2" data-number="3.13">
<h2 data-number="3.13" class="anchored" data-anchor-id="florence-nightingales-data"><span class="header-section-number">3.13</span> Florence Nightingale’s data</h2>
<p>It’s possible to create the coxcomb plot in R: see the documentation of Histdata.</p>
<p>Florence Nightingale’s plot of mortality during the Crimean War is a famous early example of data display. It is a polar area diagram, also known as a coxcomb plot. Note: it is not a pie chart.</p>
<ul>
<li><p>Based on looking at both the static and the animated version of the data, explain what the data shows about the primary causes of death during the Crimean War.</p></li>
<li><p>Name two advantages that make this data display particularly effective at communicating the data.</p></li>
<li><p>Name two disadvantages that make this data display confusing or ineffective.</p></li>
<li><p>What is another way to display the same information, and how would it address the problems that you identified? Name both the type of display and exactly what you would plot.</p></li>
</ul>
<p>Why is the following plot better than the coxcomb plot?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(Disease.rate <span class="sc">+</span> Wounds.rate <span class="sc">+</span> Other.rate <span class="sc">~</span> Date, <span class="at">data=</span>Nightingale, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"l"</span>), <span class="at">auto.key=</span>T, <span class="at">ylab=</span><span class="st">"Annual rate of deaths per 1000"</span>, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="at">xlab =</span> <span class="st">"Date (year-month)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="births-by-day-of-year" class="level2" data-number="3.14">
<h2 data-number="3.14" class="anchored" data-anchor-id="births-by-day-of-year"><span class="header-section-number">3.14</span> Births by day of year</h2>
<p>This plot shows the number of US births by the day of the year in 1978.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span> (births <span class="sc">~</span> day_of_year, <span class="at">data=</span>Births78, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"smooth"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Notice that the data are grouped. What proportion of the data are in the lower group, approximately? What are these data points?</p>
<p>Define new variable weekend to be 1 if Sat or Sun, 0 if any other day. Now view the data again with the command View(Births78) and then plot the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>Births78<span class="sc">$</span>weekend<span class="ot">=</span>Births78<span class="sc">$</span>wday<span class="sc">==</span><span class="st">"Sun"</span> <span class="sc">|</span> Births78<span class="sc">$</span>wday<span class="sc">==</span><span class="st">"Sat"</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(births <span class="sc">~</span> day_of_year, <span class="at">groups=</span>weekend, <span class="at">data=</span>Births78, <span class="at">auto.key=</span>T,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"smooth"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="womens-weights-and-heights" class="level2" data-number="3.15">
<h2 data-number="3.15" class="anchored" data-anchor-id="womens-weights-and-heights"><span class="header-section-number">3.15</span> Women’s weights and heights</h2>
<p>Make a simple scatterplot of the average heights and weights of women in the US from an unspecified year. You can execute the below commands by pasting them into the command box.</p>
<p>Load data into memory. We use a built-in dataset of women, their heights, and weights. Look at the dataset by typing the name of it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(women)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Make a simple scatterplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(weight <span class="sc">~</span> height, <span class="at">data=</span>women)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Improve the scatterplot a bit by labeling the axes and giving it a title. Also, change the plotting character from an open circle to a closed circle. Do a linear regression of weight on height, and draw the regression line on the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(weight <span class="sc">~</span> height, <span class="at">data=</span>women, <span class="at">xlab=</span><span class="st">"Height (inches)"</span>, <span class="at">ylab=</span><span class="st">"Average weight (pounds)"</span>, <span class="at">main=</span><span class="st">"Average weights by height for US women in an unknown year"</span>, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Create a new variable for body mass index (BMI) for each height/average-weight combination in this dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>bmi<span class="ot">=</span><span class="dv">703</span><span class="sc">*</span>women<span class="sc">$</span>weight<span class="sc">/</span>women<span class="sc">$</span>height<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plot average BMI by height</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(bmi <span class="sc">~</span> height, <span class="at">data=</span>women, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"p"</span>), <span class="at">xlab=</span><span class="st">"Height (inches)"</span>, <span class="at">ylab=</span><span class="st">"Average BMI (kg/m^2)"</span>, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">"Average BMI by height for US women in an unknown year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>Currently, about 2/3 of American women are overweight (BMI between 25 and 30) or obese (BMI more than 30), a trend that began in the early 1990s. Do you think that these data are recent, or do they predate the “epidemic” of overweight and obesity? Explain your answer.</p></li>
<li><p>The goal of the BMI is to assess weight independent of height. Based on your scatterplot, do you think that BMI succeeds in doing that? Explain why. If there is a group of women for whom BMI succeeds as a measurement of weight independent of height, specify it.</p></li>
</ul>
</section>
<section id="esophageal-cancer-case-control-data" class="level2" data-number="3.16">
<h2 data-number="3.16" class="anchored" data-anchor-id="esophageal-cancer-case-control-data"><span class="header-section-number">3.16</span> Esophageal cancer case-control data</h2>
<p>These data come from a study of esophageal cancer in Ille-et-Vilaine, France. (Source: Breslow, N. E. and Day, N. E. (1980) Statistical Methods in Cancer Research. 1: The Analysis of Case-Control Studies.http://w2.iarc.fr/en/publications/pdfs-online/stat/sp32/)</p>
<p>“Cases were 200 males diagnosed with esophageal cancer in one of the regional hospitals between January 1972 and April 1974. Controls were a sample of 775 adult males drawn from electoral lists in each commune. Both types of subject were administered a detailed dietary interview. which contained questions about their consumption of tobacco and of various alcoholic beverages in addition to those about foods.”</p>
<p>Load and summarize the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(esoph)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(esoph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   agegp          alcgp         tobgp        ncases         ncontrols     
 25-34:15   0-39g/day:23   0-9g/day:24   Min.   : 0.000   Min.   : 0.000  
 35-44:15   40-79    :23   10-19   :24   1st Qu.: 0.000   1st Qu.: 1.000  
 45-54:16   80-119   :21   20-29   :20   Median : 1.000   Median : 4.000  
 55-64:16   120+     :21   30+     :20   Mean   : 2.273   Mean   : 8.807  
 65-74:15                                3rd Qu.: 4.000   3rd Qu.:10.000  
 75+  :11                                Max.   :17.000   Max.   :60.000  </code></pre>
</div>
</div>
<p>Plot the ratio of cases to controls versus age, alcohol consumption, and tobacco consumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(ncases<span class="sc">/</span>ncontrols <span class="sc">~</span> agegp, <span class="at">data=</span>esoph, <span class="at">xlab=</span><span class="st">"Age (years)"</span>, </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="at">ylab=</span><span class="st">"Ratio of cases to controls"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(ncases<span class="sc">/</span>ncontrols <span class="sc">~</span> alcgp, <span class="at">data=</span>esoph, <span class="at">xlab=</span><span class="st">"Alcohol consumption (grams/day)"</span>, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="at">ylab=</span><span class="st">"Ratio of cases to controls"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(ncases<span class="sc">/</span>ncontrols <span class="sc">~</span> tobgp, <span class="at">data=</span>esoph, <span class="at">xlab=</span><span class="st">"Tobacco consumption (grams/day)"</span>, </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="at">ylab=</span><span class="st">"Ratio of cases to controls"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on these plots, does alcohol or tobacco seem to be most strongly associated with esophageal cancer? Explain your answer.</p>
</section>
<section id="map-data" class="level2" data-number="3.17">
<h2 data-number="3.17" class="anchored" data-anchor-id="map-data"><span class="header-section-number">3.17</span> Map data</h2>
<p>R can also plot maps using additional packages. This example comes from the book Flowing Data by Nathan Yau. Note that he chooses to use hexadecimal numbers for colors instead of names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>fertility<span class="ot">=</span><span class="fu">read.csv</span>(<span class="st">"http://book.flowingdata.com/ch08/points/adol-fertility.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This map plots adolescent fertility for each country by latitude and longitude. In demographics, fertility refers to the number of births, which is a term in contrast to conversational English. (Fecundability in demographics refers to the ability to become pregnant and give birth, which is what is called fertility in conversational English.) Circles are proportional to fertility rate for adolescents. Why is a square root scaling useful?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(<span class="sc">~</span>ad_fert_rate, <span class="at">data=</span>fertility)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">map</span>(<span class="st">"world"</span>, <span class="at">fill=</span>F, <span class="at">col=</span><span class="st">"#cccccc"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">symbols</span>(fertility<span class="sc">$</span>longitude, fertility<span class="sc">$</span>latitude, <span class="at">circles=</span><span class="fu">sqrt</span>(fertility<span class="sc">$</span>ad_fert_rate), <span class="at">add=</span>T, <span class="at">inches=</span><span class="fl">0.15</span>, <span class="at">bg=</span><span class="st">"#03ceef"</span>, <span class="at">fg=</span><span class="st">"#ffffff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="summarizing-data-in-r" class="level2" data-number="3.18">
<h2 data-number="3.18" class="anchored" data-anchor-id="summarizing-data-in-r"><span class="header-section-number">3.18</span> Summarizing data in R</h2>
</section>
<section id="data-are-data-frames" class="level2" data-number="3.19">
<h2 data-number="3.19" class="anchored" data-anchor-id="data-are-data-frames"><span class="header-section-number">3.19</span> Data are data frames</h2>
<p>As before, we’ll use data from Health Evaluation and Linkage to Primary (HELP) care randomized clinical trial (RCT), which followed n=470 subjects without primary care enrolled in detox in Boston circa 2000, followed for up to 2 years, every six months. Before you analyze data, you should look at the data frame with the {} and {} commands to make sure it looks like you expect: the appropriate number of observations and variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="numerical-summaries-one-categorical-and-one-quantitative-variable" class="level3" data-number="3.19.1">
<h3 data-number="3.19.1" class="anchored" data-anchor-id="numerical-summaries-one-categorical-and-one-quantitative-variable"><span class="header-section-number">3.19.1</span> Numerical summaries: one categorical and one quantitative variable</h3>
<p>R has the expected tools for data summaries: mean, median, sd</p>
<p>Mosaic also includes a command to do many data summaries at once: favstats.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(<span class="sc">~</span>age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapt1_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span>age, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> min Q1 median Q3 max     mean       sd   n missing
  19 30     35 40  60 35.65342 7.710266 453       0</code></pre>
</div>
</div>
<p>On average, both mean and median, the participants are about 35 years old.</p>
<p>We can also summarize data by groups. The following commands from Mosaic are equivalent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(age <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  substance min Q1 median    Q3 max     mean       sd   n missing
1   alcohol  20 33   38.0 43.00  58 38.19774 7.652272 177       0
2   cocaine  23 30   33.5 37.25  60 34.49342 6.692881 152       0
3    heroin  19 27   33.0 39.00  55 33.44355 7.986068 124       0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span>age, <span class="at">groups=</span>substance, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  substance min Q1 median    Q3 max     mean       sd   n missing
1   alcohol  20 33   38.0 43.00  58 38.19774 7.652272 177       0
2   cocaine  23 30   33.5 37.25  60 34.49342 6.692881 152       0
3    heroin  19 27   33.0 39.00  55 33.44355 7.986068 124       0</code></pre>
</div>
</div>
<p>We can also find means stratified by two factors simultaneously:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(age <span class="sc">~</span> substance <span class="sc">|</span> sex, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>alcohol.female cocaine.female  heroin.female   alcohol.male   cocaine.male 
      39.16667       34.85366       34.66667       37.95035       34.36036 
   heroin.male         female           male 
      33.05319       36.25234       35.46821 </code></pre>
</div>
</div>
<p>When the categorical variable is binary, we can test for significance with a t.test or Wilcoxon test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(age <span class="sc">~</span> sex, <span class="at">data=</span>HELPrct) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  age by sex
t = 0.92976, df = 179.74, p-value = 0.3537
alternative hypothesis: true difference in means between group female and group male is not equal to 0
95 percent confidence interval:
 -0.8800365  2.4482932
sample estimates:
mean in group female   mean in group male 
            36.25234             35.46821 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(age <span class="sc">~</span> sex, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  age by sex
W = 19510, p-value = 0.3981
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>When the categorical variable is not binary, we can test for significance with a linear regression or a Kruskal-Wallis test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(age <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  age by substance
Kruskal-Wallis chi-squared = 34.04, df = 2, p-value = 4.058e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(age <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ substance, data = HELPrct)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.1977  -5.4435  -0.4934   4.5565  25.5066 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       38.1977     0.5593  68.297  &lt; 2e-16 ***
substancecocaine  -3.7043     0.8228  -4.502 8.59e-06 ***
substanceheroin   -4.7542     0.8714  -5.456 8.06e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.441 on 450 degrees of freedom
Multiple R-squared:  0.07279,   Adjusted R-squared:  0.06867 
F-statistic: 17.66 on 2 and 450 DF,  p-value: 4.122e-08</code></pre>
</div>
</div>
<p>We will discuss the meaning of these tests in subsequent class sessions.</p>
</section>
</section>
<section id="tables-in-r-two-categorical-variables" class="level2" data-number="3.20">
<h2 data-number="3.20" class="anchored" data-anchor-id="tables-in-r-two-categorical-variables"><span class="header-section-number">3.20</span> Tables in R: two categorical variables</h2>
<p>We can make cross-tabulations in R easily, using the Mosaic command tally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>sex, <span class="at">data=</span>HELPrct) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sex
female   male 
   107    346 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>substance, <span class="at">data=</span>HELPrct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>substance
alcohol cocaine  heroin 
    177     152     124 </code></pre>
</div>
</div>
<p>tally can show counts, proportions, or percents, and it can show margins.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(sex <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct, <span class="at">format=</span><span class="st">"count"</span>, <span class="at">margins=</span>T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        substance
sex      alcohol cocaine heroin
  female      36      41     30
  male       141     111     94
  Total      177     152    124</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(sex <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct, <span class="at">format=</span><span class="st">"proportion"</span>, <span class="at">margins=</span>F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        substance
sex        alcohol   cocaine    heroin
  female 0.2033898 0.2697368 0.2419355
  male   0.7966102 0.7302632 0.7580645</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(sex <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct, <span class="at">format=</span><span class="st">"percent"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        substance
sex       alcohol  cocaine   heroin
  female 20.33898 26.97368 24.19355
  male   79.66102 73.02632 75.80645</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tally</span>(<span class="sc">~</span>sex <span class="sc">+</span> substance, <span class="at">data=</span>HELPrct, <span class="at">format=</span><span class="st">"percent"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        substance
sex        alcohol   cocaine    heroin
  female  7.947020  9.050773  6.622517
  male   31.125828 24.503311 20.750552</code></pre>
</div>
</div>
<section id="analyzing-data-in-tables" class="level3" data-number="3.20.1">
<h3 data-number="3.20.1" class="anchored" data-anchor-id="analyzing-data-in-tables"><span class="header-section-number">3.20.1</span> Analyzing data in tables</h3>
<p>Several tests are possible: chi-square, McNemar. The McNemar test is for non-independent observations (e.g., comparison of the same subject over time.)</p>
<p>The chi-square test takes a table as input.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">tally</span>(sex <span class="sc">~</span> substance, <span class="at">data=</span>HELPrct)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tally(sex ~ substance, data = HELPrct)
X-squared = 2.0264, df = 2, p-value = 0.3631</code></pre>
</div>
</div>
</section>
</section>
<section id="two-continuous-variables" class="level2" data-number="3.21">
<h2 data-number="3.21" class="anchored" data-anchor-id="two-continuous-variables"><span class="header-section-number">3.21</span> Two continuous variables</h2>
<section id="r-data-object-manipulation-apply" class="level3" data-number="3.21.1">
<h3 data-number="3.21.1" class="anchored" data-anchor-id="r-data-object-manipulation-apply"><span class="header-section-number">3.21.1</span> R data object manipulation: apply</h3>
<p>We’ve learned how to sum all the elements in a vector or matrix, but what if we want to sum only the columns or rows? We can use the apply command to apply a command to rows or columns of a matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>test.matrix<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>), <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow=</span>T) </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>test.matrix </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(test.matrix, <span class="dv">2</span>, sum) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  6  8 10 12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(test.matrix, <span class="dv">1</span>, sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10 26</code></pre>
</div>
</div>
<p>The apply command is useful if we want to look for missing data in a dataset and see how many of each values are missing in the dataset.</p>
<p>We can go one by one through all of the variables in the dataset to see how many missing values they have using the is.na command. The HELPrct dataset has 27 variables, however, so it would take 27 commands to review that information. Instead, we can use apply to find out how many observations are missing from each variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(HELPrct) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 453  30</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HELPrct) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "age"              "anysubstatus"     "anysub"           "cesd"            
 [5] "d1"               "daysanysub"       "dayslink"         "drugrisk"        
 [9] "e2b"              "female"           "sex"              "g1b"             
[13] "homeless"         "i1"               "i2"               "id"              
[17] "indtot"           "linkstatus"       "link"             "mcs"             
[21] "pcs"              "pss_fr"           "racegrp"          "satreat"         
[25] "sexrisk"          "substance"        "treat"            "avg_drinks"      
[29] "max_drinks"       "hospitalizations"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(HELPrct<span class="sc">$</span>age)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(HELPrct<span class="sc">$</span>anysub)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 207</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(<span class="fu">apply</span>(HELPrct, <span class="dv">2</span>, is.na), <span class="dv">2</span>, sum) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             age     anysubstatus           anysub             cesd 
               0              207              207                0 
              d1       daysanysub         dayslink         drugrisk 
               0              209               22                1 
             e2b           female              sex              g1b 
             239                0                0                0 
        homeless               i1               i2               id 
               0                0                0                0 
          indtot       linkstatus             link              mcs 
               0               22               22                0 
             pcs           pss_fr          racegrp          satreat 
               0                0                0                0 
         sexrisk        substance            treat       avg_drinks 
               0                0                0                0 
      max_drinks hospitalizations 
               0                0 </code></pre>
</div>
</div>
<p>We can notice that the variables with the most missing data (missing 207, 209, and 239 observations) are missing responses from about half of the sample. That fact is important to note because any analysis that includes these variables will have half the sample size compared with an analysis that doesn’t use those variables.</p>
</section>
</section>
<section id="exercise-1" class="level2" data-number="3.22">
<h2 data-number="3.22" class="anchored" data-anchor-id="exercise-1"><span class="header-section-number">3.22</span> Exercise</h2>
<p>In February 2015, the New England Journal of Medicine published a randomized controlled trial that assigned infants ages 4–11 months to be introduced to peanuts or to avoid peanuts. The study found that infants introduced to peanuts had much lower prevalence of peanut allergy at age 5 years old than infants who avoided peanuts: 3% among peanut eaters versus 17% among avoiders in intention-to-treat analysis. The study included the following plots. (George Du Toit, et al.&nbsp;Randomized Trial of Peanut Consumption in Infants at Risk for Peanut Allergy, NEJM. 2015; 372:803–813.)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/peanut-study-graphics.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Plot from peanut consumption in infants at risk for peanut allergy</figcaption><p></p>
</figure>
</div>
<ul>
<li><p>Describe how wheal sizes differed between the peanut avoidance and peanut consumption groups, and how they changed over time. Support your answer with reference to specific components of the data displays.</p></li>
<li><p>Describe how peanut specific IgE differed between the peanut avoidance and peanut consumption groups, and how they changed over time. Support your answer with reference to specific components of the data displays.</p></li>
<li><p>Why did the authors show both individual and aggregate measures in this data display?</p></li>
<li><p>Assuming that the above data displays are accurate, in your opinion, are these effective displays of the data? Explain your answer.</p></li>
<li><p>The authors used graphical data displays instead of tables in their paper. The paper included zero tables. Why might they have used data displays instead of tables, in your opinion?</p></li>
</ul>
<section id="suggested-answers" class="level3" data-number="3.22.1">
<h3 data-number="3.22.1" class="anchored" data-anchor-id="suggested-answers"><span class="header-section-number">3.22.1</span> Suggested answers</h3>
<ul>
<li>Describe how wheal sizes differed between the peanut avoidance and peanut consumption groups, and how they changed over time. Support your answer with reference to specific components of the data displays. Any reasonable answer will get credit.</li>
</ul>
<p>The wheal sizes were bigger in the peanut avoidance group than in the peanut consumption group, both on average and individually. We can see the average wheal size as the dark black line which is practically zero in the peanut consumption group, but the mean is not zero and increases with time in the peanut avoidance group. We can see the individual wheal sizes among those allergic to peanuts as the red lines on the plot and notice only one person in the peanut consumption group had a peanut allergy and their wheal sizes increased over time, whereas many people in the peanut avoidance group had peanut allergies, and their wheal sizes increased over time. We can also notice that many children eating peanuts had nonzero wheal sizes, but they were not allergic. Wheal sizes were generally larger in the avoidance group, though.</p>
<ul>
<li><p>Describe how peanut specific IgE differed between the peanut avoidance and peanut consumption groups, and how they changed over time. Support your answer with reference to specific components of the data displays.Any reasonable answer will get credit.<br>
Peanut specific IgE differed between the two groups, as we described for the skin wheal size. The patterns both on average and at mean were similar as we described above.</p></li>
<li><p>Why did the authors show both individual and aggregate measures in this data display?</p></li>
</ul>
<p>Showing both individual and mean measures in a data display lets readers decide for themselves what the data shows. We can see patterns in both the mean and individual data, and the patterns are the same. Any reasonable answer will get credit.</p>
<ul>
<li>Assuming that the above data displays are accurate, in your opinion, are these effective displays of the data? Explain your answer.</li>
</ul>
<p>I think these are effective displays of the data. They show a lot of information without overwhelming the reader. Every bit of ink is useful and conveys useful information to the reader. Any reasonable answer will get credit.</p>
<ul>
<li>The authors used graphical data displays instead of tables in their paper. The paper included zero tables. Why might they have used data displays instead of tables, in your opinion?</li>
</ul>
<p>The authors manage to display more information in these plots then would’ve been reasonable to put into a table. The readers of this article are busy doctors who do not have time to read tables, so the authors took time to figure out how to convey the information in an easy to read format that allows readers to see both individual and average trends over time. Making a table might be easier, but it would probably only show the average, which gives less useful information. A reader seeing this paper might wonder about individual variation from the mean because peanut allergies are so severe and sometimes means to conceal information. For example the reader might wonder whether any individuals in the peanut consumption group developed highly severe allergies, but this data display answers their question about how individuals vary from the group by showing wheal size and IgE levels for every participant, and we see that the one peanut allergic person in the peanut consumption group had relatively low wheal size and IgE levels, compared to those in the peanut avoidance group. Showing every individual in a table would not be feasible.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chaptA.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapt2.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Identifying research questions and data sources</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>